version: '3.1'
services:
  postgresql:
    image: postgresql:latest
    ports:
      - '9999:9999'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
      - POSTGRES_USER=fimena